PROP = range(8)

VIP_START = 0
VIP_END = 0
VIP_STEP = 100

G_START = 8
G_END = 8
G_STEP = 1

BG_START = 4
BG_END = 4
BG_STEP = 1

localrules: all, create

rule all:
    input:
        expand('scans/{a}_{b}_{c}_{d}/ai.dat',
            a=PROP,
            b=range(VIP_START, VIP_END + VIP_STEP, VIP_STEP),
            c=range(G_START, G_END + G_STEP, G_STEP),
            d=range(BG_START, BG_END + BG_STEP, BG_STEP))
    shell:
        '''
        python analysis_gs.py {input}
        mkdir -p png
        mv *.png png
        cp * scans/
        '''

rule create:
    output:
        expand('scans/{a}_{b}_{c}_{d}.pickle',
            a=PROP,
            b=range(VIP_START, VIP_END + VIP_STEP, VIP_STEP),
            c=range(G_START, G_END + G_STEP, G_STEP),
            d=range(BG_START, BG_END + BG_STEP, BG_STEP))
    shell:
        '''
        python microcircuit/create_params.py {output}
        mkdir -p scans/microcircuit/
        cp -r microcircuit/ scans/microcircuit/        
        '''

rule simulate:
    input: 'scans/{a}_{b}_{c}_{d}.pickle'
    output: 'scans/{a}_{b}_{c}_{d}/ai.dat'
    shell:
        '''
        python -W ignore run_network.py {input} {output}
        '''
