F1 = range(800, 1201, 200)
F2 = range(1000, 1401, 200)
F3 = range(1000, 1201, 200)
F4 = range(1000, 1201, 200)

localrules: all, create

rule all:
    input:
        expand('scans/{a}_{b}_{c}_{d}/ai.dat',
            a=F1,
            b=F2,
            c=F3,
            d=F4)
    shell:
        '''
        python scans/scan_data.py {input}
        mkdir -p scans/png
        mv scans/*.png scans/png
        '''

rule create:
    output:
        expand('scans/{a}_{b}_{c}_{d}.pickle',
            a=F1,
            b=F2,
            c=F3,
            d=F4)
    shell:
        '''
        python microcircuit/create_params.py {output}
        mkdir -p scans/
        cp -r microcircuit/ scans/
        '''

rule simulate:
    input: 'scans/{a}_{b}_{c}_{d}.pickle'
    output: 'scans/{a}_{b}_{c}_{d}/ai.dat'
    shell:
        '''
        python -W ignore run_network.py {input} {output}
        '''
