Us = '0.05-0.1-0.05'
Fs = '0.0-1000.0-20.0'
Ds = '0.0-1000.0-20.0'
n_bestpoints = 20
n_dataset = 32
exp_data = 'exp-data_04.json'

rule all:
    input:
        expand('stp-data/done_{a}', a=range(n_dataset))
    output:
        'stp_fitted.pickle'
    shell:
        '''
        python -W ignore stp_save.py
        mv stp:*.csv stp:*.png stp-results/
        mv stp:*.pickle prog.*.txt stp-data/
        '''

rule get:
    input:
        exp_data
    output:
        expand('stp-data/exp-dict_{a}.pickle', a=range(n_dataset))
    shell:
        '''
        mkdir -p stp-data/ stp-results/
        python -W ignore stp_get.py {input} {output}
        '''

rule run:
    input:
        'stp-data/exp-dict_{a}.pickle'
    output:
        'stp-data/done_{a}'
    shell:
        '''
        python -W ignore stp_fitting.py {input} {Us} {Fs} {Ds} {n_bestpoints}
        > {output}
        '''
