article = 'Lefort-Petersen-2017'
pretype = 'L4-Exc'
posttype = 'L4-Exc'
spk_isi = 10
pprs = '1.0-0.69'
peaks = 'None'
U = range(10, 12, 1) # max 20 levels (0.05:1.0:0.05)
F = range(10, 12, 1) # max 101 levels (0:1000:10)
D = range(10, 12, 1)

localrules: all

rule all:
    input:
        expand('{a}_{b}_{c}_.dat', a = U, b = F, c = D)
    shell:
        '''
        python -W ignore stp_evaluate.py {article} {input}
        rm {input}
        '''

rule create:
    output:
        expand('{a}_{b}_{c}_.pickle', a = U, b = F, c = D)
    shell:
        '''
        python -W ignore stp_create.py {pretype} {posttype} {spk_isi} {pprs} {peaks} {output}
        '''

rule run:
    input:
        '{a}_{b}_{c}_.pickle'
    output:
        '{a}_{b}_{c}_.dat'
    shell:
        '''
        python -W ignore stp_test.py {input} {output}
        rm {input}
        '''
