F1_COUNT = 8
F2_COUNT = 10

localrules: all, create

rule all:
    input:
        expand('scans/{a}_{b}_6_4/lts_distr.npy',
            a=range(F1_COUNT),
            b=range(F2_COUNT))
    output:
        expand('{a}_ltc-distr.png', a=range(F1_COUNT))
    shell:
        '''
        python ltc_distr.py {input}
        '''

rule create:
    output:
        expand('scans/{a}_{b}_6_4.pickle',
            a=range(F1_COUNT),
            b=range(F2_COUNT))
    shell:
        '''
        python microcircuit/create_params.py {output}
        mkdir -p scans/microcircuit/
        cp microcircuit/*.py scans/microcircuit/
        mkdir -p scans/stp/
        cp stp/*.py scans/stp/
        mkdir -p scans/conn_probs/
        cp conn_probs/* scans/conn_probs/
        '''

rule simulate:
    input: 'scans/{a}_{b}_{c}_{d}.pickle'
    output: 'scans/{a}_{b}_{c}_{d}/lts_distr.npy'
    shell:
        '''
        python -W ignore run_network.py {input} {output}
        '''
