localrules: all

rule all:
    input:
        'data/fr.dat'        
    shell:
        '''
        > done
        '''

rule run:
    input:
        'run_network.py'        
    output:
        'data/fr.dat'
    shell:
        '''
        python -W ignore run_network.py
        '''
